version: '3.8'

services:
  db:
    image: docker.io/library/mysql
    restart: always
    networks:
      - backend
    cap_add:
      - SYS_NICE
    volumes:
      - mysql_data:/var/lib/mysql:Z
      - ./api-server/db-setup.sql:/docker-entrypoint-initdb.d/setup.sql:Z
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  nginx:
    depends_on:
      - api
      - ui
    restart: always
    networks:
      - frontend
      - backend
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  api:
    networks:
      - backend
    build:
      context: ./api-server
      target: dev
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - db
    volumes:
      - ./api-server:/src:Z
      - /src/node_modules
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      NODE_ENV: development
  
  ui:
    networks:
      - frontend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./blog-ui
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    volumes:
      - ./blog-ui:/src:Z
      - /src/node_modules

networks:
  frontend:
  backend:

volumes:
  mysql_data:
