global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'node_vm1'
    static_configs:
      - targets: ['vm-app.app.local:9100']

  - job_name: 'cadvisor_vm1'
    static_configs:
      - targets: ['vm-app.app.local:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']